user  nginx;
worker_processes  3;  ## Default: 1

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11;

    upstream mimir_backend {
        server mimir1:9009 max_fails=1 fail_timeout=1s;
        server mimir2:9009 max_fails=1 fail_timeout=1s;
        server mimir3:9009 max_fails=1 fail_timeout=1s backup;
    }

    server {
        listen 9009;
        location / {
            proxy_pass http://mimir_backend;
        }
    }
}
