user  nginx;
worker_processes  3;  ## Default: 1

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11;

    # Default tempo port
    upstream tempo_3200 {
        server tempo1:3200 max_fails=1 fail_timeout=1s;
        server tempo2:3200 max_fails=1 fail_timeout=1s;
        server tempo3:3200 max_fails=1 fail_timeout=1s backup;
    }

    server {
        listen 3200;
        location / {
            proxy_pass http://tempo_3200;
        }
    }

    # Opentelemetry grpc port
    upstream tempo_4317 {
        server tempo1:4317 max_fails=1 fail_timeout=1s;
        server tempo2:4317 max_fails=1 fail_timeout=1s;
        server tempo3:4317 max_fails=1 fail_timeout=1s backup;
    }

    server {
        listen 4317;
        http2 on;
        location / {
            grpc_pass tempo_4317;
        }
    }

    # Opentelemetry http port
    upstream tempo_4318 {
        server tempo1:4318 max_fails=1 fail_timeout=1s;
        server tempo2:4318 max_fails=1 fail_timeout=1s;
        server tempo3:4318 max_fails=1 fail_timeout=1s backup;
    }

    server {
        listen 4318;
        location / {
            proxy_pass http://tempo_4318;
        }
    }
}
