#
# The original version of this file is taken from the example directory in the grafana agent repository
# You can find that here: https://github.com/grafana/agent/blob/main/example/docker-compose/docker-compose.yaml.
# The copy was taken at commit b9c3594b84e7be24fa936548782130e39636eb38
#
version: '3.7'
services:
  grafana:
    image: grafana/grafana:10.4.7@sha256:578309639f1343b02883d7d4fc2b7f3783747a9f53e7b3ec34224e92eedb55ad
    entrypoint:
      - /usr/share/grafana/bin/grafana-server
      - --homepath=/usr/share/grafana
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ./grafana/config:/etc/grafana-config
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:3.1.1@sha256:e689cc634841c937de4d7ea6157f17e29cf257d6a320f1c293ab18d46cfea986
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  mimir:
    image: grafana/mimir:2.9.0@sha256:dba11782c968d585558793598e5000480c0c3d0c611fee21dc5d59fd9fb837ad
    volumes:
      - ./mimir/config:/etc/mimir-config
    entrypoint:
      - /bin/mimir
      - -config.file=/etc/mimir-config/mimir.yaml
    ports:
      - "9009:9009"

  tempo:
    image: grafana/tempo:2.1.0@sha256:db8a80ce69515e100f6dd1777651dae4e74f18b9d711c4ba0f41c4f610dc443b
    command:
      - "-storage.trace.backend=local"                  # tell tempo where to permanently put traces
      - "-storage.trace.local.path=/tmp/tempo/traces"
      - "-storage.trace.wal.path=/tmp/tempo/wal"        # tell tempo where to store the wal
      - "-auth.enabled=false"                           # disables the requirement for the X-Scope-OrgID header
      - "-server.http-listen-port=3200"
    ports:
      - "3200:3200"
      - "4317:4317"

volumes:
  elasticsearch_data:
    driver: local
