{
 "title": "MinIO Cluster Replication Dashboard",
 "description": "MinIO Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Received Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_received_bytes{job=\"minio\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Received Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_received_count{job=\"minio\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Sent Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (endpoint,server) (minio_cluster_replication_sent_bytes{job=\"minio\"})",
     "legendFormat": "{{endpoint}},{{server}}"
    }
   ]
  },
  {
   "title": "Sent Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (endpoint,server) (minio_cluster_replication_sent_count{job=\"minio\"})",
     "legendFormat": "{{endpoint}},{{server}}"
    }
   ]
  },
  {
   "title": "Failed Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_total_failed_bytes{job=\"minio\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Failed Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_total_failed_count{job=\"minio\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Total Failed Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (endpoint,server) (minio_cluster_replication_total_failed_bytes{job=\"minio\"})",
     "legendFormat": "{{endpoint}},{{server}}"
    }
   ]
  },
  {
   "title": "Total Failed Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (endpoint,server) (minio_cluster_replication_total_failed_count{job=\"minio\"})",
     "legendFormat": "{{endpoint}},{{server}}"
    }
   ]
  },
  {
   "title": "Last Hour Failed Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (endpoint,server) (minio_cluster_replication_last_hour_failed_bytes{job=\"minio\"})",
     "legendFormat": "{{endpoint}},{{server}}"
    }
   ]
  },
  {
   "title": "Last Hour Failed Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (endpoint,server) (minio_cluster_replication_last_hour_failed_count{job=\"minio\"})",
     "legendFormat": "{{endpoint}},{{server}}"
    }
   ]
  },
  {
   "title": "Last Minute Failed Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (endpoint,server) (minio_cluster_replication_last_minute_failed_bytes{job=\"minio\"})",
     "legendFormat": "{{endpoint}},{{server}}"
    }
   ]
  },
  {
   "title": "Last Minute Failed Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (endpoint,server) (minio_cluster_replication_last_minute_failed_count{job=\"minio\"})",
     "legendFormat": "{{endpoint}},{{server}}"
    }
   ]
  },
  {
   "title": "Total Proxied Head Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_head_requests_total{job=\"minio\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Head Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_head_requests_failures{job=\"minio\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Put Tag Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_put_tagging_requests_total{job=\"minio\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Put Tag Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_put_tagging_requests_failures{job=\"minio\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Get Tag Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_get_tagging_requests_total{job=\"minio\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Get Tag Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_get_tagging_requests_failures{job=\"minio\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Delete Tag Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_delete_tagging_requests_total{job=\"minio\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Delete Tag Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_delete_tagging_requests_failures{job=\"minio\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Get Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_get_requests_total{job=\"minio\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Get Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_get_requests_failures{job=\"minio\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}